apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-deployment-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
